### ISSUE TITLE
flanneld.service Before=early-docker ??

### ISSUE THREAD

**Issue by psi-4ward** [coreos/coreos-overlay#1226]
flanneld.service looks like
```
[Unit]
Description=Network fabric for containers
Documentation=https://github.com/coreos/flannel
Wants=etcd.service
Requires=early-docker.service
After=etcd.service early-docker.service
Before=early-docker.target
```

and im wondering about 
```
After=early-docker.service
Before=early-docker.target
```

After and Before?

**Comment by crawford** [comment]
On 04/27, Christoph Wiechert wrote:
> and im wondering about 
> ```
> After=early-docker.service
> Before=early-docker.target
> ```
> 
> After and Before?

This will cause flannel to run after early-docker.service (because
flannel runs within a docker container), but before the target is
fulfilled. It's necessary to ensure flannel starts before the target
because docker.service depends (Requires and After) on
early-docker.target so that it's containers have the overlay network
available.

-Alex

**Comment by psi-4ward** [comment]
Uh nice! Never heard this systemd feature.

Thank you very much!
